"""add manual_extra_order_id to routes

Revision ID: 11c07e8d5bdc
Revises: d4900eab0b15
Create Date: 2026-08-31 11:38:08.251478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c07e8d5bdc'
down_revision: Union[str, None] = 'd4900eab0b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_extra_order_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('manual_extra_order_id')

    # ### end Alembic commands ###
