"""initial normalized schema

Revision ID: 483841faae7a
Revises: 
Create Date: 2026-08-07 11:42:51.892272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483841faae7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_car_count', sa.Integer(), nullable=True),
    sa.Column('default_bike_count', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geocoding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_key', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geocoding_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geocoding_cache_address_key'), ['address_key'], unique=True)

    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('generated_routes', sa.Integer(), nullable=True),
    sa.Column('pending_orders_count', sa.Integer(), nullable=True),
    sa.Column('failed_orders_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failed_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('entered_address', sa.String(), nullable=True),
    sa.Column('edited_address', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failed_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failed_addresses_order_id'), ['order_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('delivery_slot', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_vehicle', sa.String(), nullable=True),
    sa.Column('geocode_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_id'), ['order_id'], unique=False)

    op.create_table('route_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('available_cars', sa.Integer(), nullable=True),
    sa.Column('available_bikes', sa.Integer(), nullable=True),
    sa.Column('route_count', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_plan_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['route_plan_id'], ['route_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_plan_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('driver', sa.String(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_duration_minutes', sa.Float(), nullable=True),
    sa.Column('estimated_finish_time', sa.String(), nullable=True),
    sa.Column('utilization_percent', sa.Float(), nullable=True),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_auto_created', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['route_plan_id'], ['route_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('travel_distance_km', sa.Float(), nullable=True),
    sa.Column('travel_time_minutes', sa.Float(), nullable=True),
    sa.Column('eta', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_stops')
    op.drop_table('routes')
    op.drop_table('pending_orders')
    op.drop_table('route_plans')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('failed_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failed_addresses_order_id'))

    op.drop_table('failed_addresses')
    op.drop_table('upload_batches')
    with op.batch_alter_table('geocoding_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geocoding_cache_address_key'))

    op.drop_table('geocoding_cache')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
