"""add save-to-history fields to route_plans

Revision ID: 73c69ecbb14b
Revises: 483841faae7a
Create Date: 2026-08-07 12:16:15.800899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c69ecbb14b'
down_revision: Union[str, None] = '483841faae7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        # server_default so every pre-existing row (all created before this
        # feature existed, so none of them were ever explicitly "saved") is
        # backfilled to False instead of failing the NOT NULL constraint.
        batch_op.add_column(sa.Column('is_saved', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True))

    # The server_default above only exists to backfill existing rows during
    # this migration - drop it afterward so the ORM's Python-side default
    # (models.py) stays the single source of truth for new rows going
    # forward, same as every other column in this app.
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.alter_column('is_saved', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.drop_column('saved_at')
        batch_op.drop_column('label')
        batch_op.drop_column('is_saved')

    # ### end Alembic commands ###
