"""add drivers, driver sessions, location pings, route driver fields

Revision ID: 787c6ab9d186
Revises: f3a91c7b2e10
Create Date: 2026-08-21 15:33:02.944948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787c6ab9d186'
down_revision: Union[str, None] = 'f3a91c7b2e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_salt', sa.String(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_driver_code'), ['driver_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_username'), ['username'], unique=True)

    op.create_table('driver_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_sessions_token'), ['token'], unique=True)

    op.create_table('driver_location_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_location_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_location_pings_recorded_at'), ['recorded_at'], unique=False)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        # server_default backfills every existing row (132+ in production) -
        # without it, adding a NOT NULL column to a non-empty table fails
        # outright. Matches the model's Python-side default('planned') for
        # rows inserted after this point.
        batch_op.add_column(sa.Column('route_run_status', sa.String(), nullable=False, server_default='planned'))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(
            'fk_routes_driver_id_drivers', 'drivers', ['driver_id'], ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_routes_driver_id_drivers', type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('route_run_status')
        batch_op.drop_column('driver_id')

    with op.batch_alter_table('driver_location_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_location_pings_recorded_at'))

    op.drop_table('driver_location_pings')
    with op.batch_alter_table('driver_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_sessions_token'))

    op.drop_table('driver_sessions')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_username'))
        batch_op.drop_index(batch_op.f('ix_drivers_driver_code'))

    op.drop_table('drivers')
    # ### end Alembic commands ###
