"""add column_order to upload_batches

Revision ID: be5c1de780e7
Revises: cc29eb9bb8f7
Create Date: 2026-08-08 15:36:05.858102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5c1de780e7'
down_revision: Union[str, None] = 'cc29eb9bb8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_order', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_column('column_order')

    # ### end Alembic commands ###
