"""add delivery status to route stops

Revision ID: d4900eab0b15
Revises: 787c6ab9d186
Create Date: 2026-08-22 15:27:57.977610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4900eab0b15'
down_revision: Union[str, None] = '787c6ab9d186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate omitted server_default on the NOT NULL delivery_status
    # column - would fail against every existing route_stops row otherwise
    # (same fix as 787c6ab9d186's route_run_status column before this).
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
