"""add explicit current session pointers to app_settings

Revision ID: d59431589c28
Revises: 73c69ecbb14b
Create Date: 2026-08-08 12:19:25.871432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59431589c28'
down_revision: Union[str, None] = '73c69ecbb14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session_batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_session_plan_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('current_session_plan_id')
        batch_op.drop_column('current_session_batch_id')

    # ### end Alembic commands ###
